### ISSUE TITLE
[Bug] Coordinate changing

### ISSUE THREAD

**Issue by Double13** [Powback/MapEditor#344] opened 2022-03-29 11:21 UTC
When changing the coordinates of an item via the X,Y,Z/Rot menu it resets the item back to a different sate.

The current workaround/solution is
When changing a number (lets presume X) you first need to deselect the item (select random object) before reselecting the object and change the next axis.

**Comment by FoolHen** [comment] 2022-04-15 11:59
Duplicate of https://github.com/BF3RM/MapEditor/issues/342, already fixed

**Closed as completed by FoolHen** 2022-04-15 11:59 UTC
Labels: bug
