### ISSUE TITLE
I would like a copy/paste x, y, & z field boxes contents.

### ISSUE THREAD

**Issue by Chrisdashezz** [Powback/MapEditor#383] opened 2023-04-18 02:17 UTC
I want to be able to quickly input/output XYZ fields because it makes the workflow much faster and it is extremely handy in manipulating assets.

Just to be clear, one button that copies all three fields and one button to paste.
basically tuples.

**Comment by FoolHen** [comment] 2023-04-19 18:03
Duplicate of https://github.com/BF3RM/MapEditor/issues/346

**Closed as not planned by FoolHen** 2023-04-19 18:03 UTC
