### ISSUE TITLE
[FEATURE] Ability to place assets, FX and such on separated custom folders.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#300] opened 2021-07-31 22:09 UTC
This would be useful to organize stuff better so as an example we could hide exactly what you want or find stuff easier.

![image](https://user-images.githubusercontent.com/36018654/127753453-ebacfb08-95e5-4d67-b06b-5dd1404a95f3.png)

right clicking on the empty space --> new folder --> set name
For setting the assets you want, would be right clicking on the asset you want from the asset list, then add into --> "folder name"

**Comment by FoolHen** [comment] 2021-08-01 14:05
This is planned, duplicate of https://github.com/BF3RM/MapEditor/issues/242

**Closed as completed by FoolHen** 2021-08-01 14:05 UTC
